### ISSUE TITLE
 TaintTracking::FunctionModel: `FunctionOutput.isResult()` does not correspond to `FunctionOutput.isResult(0)`

### ISSUE THREAD

**Issue by gagliardetto** [github/codeql-go#146]
### What currently happens

If a function returns only **one** result, then `FunctionOutput.isResult()` **will work**, and `FunctionOutput.isResult(0)` will **not** work.

If a function returns **two or more** results, then `FunctionOutput.isResult(0)` **will work**, and `FunctionOutput.isResult()` will **not** work.

### What IMHO would be better

It would be a lot less error-prone and a lot more awesome to be able to write `FunctionOutput.isResult(0)` regardless of whether there is one result or more.

### Why it would be an improvement over the current situation

It would be a lot harder to make errors (such as using `FunctionOutput.isResult()` when in reality the function returns more than one result) if `FunctionOutput.isResult(0)` and `FunctionOutput.isResult()` were equivalent regardless of the number of results returned by the function.

I believe this would make things simpler to the end-developer that will be writing codeql.

**Comment by gagliardetto** [comment]
Same for all other places where the usage of `*Result(0)` is valid only if `len(results) > 1`

**Comment by max-schaefer** [comment]
This sounds like a reasonable suggestion. @owen-mc, perhaps this is something you could look into once you're done with your current batch of issues?

**Comment by owen-mc** [comment]
Sure

**Comment by gagliardetto** [comment]
Thank you! :rocket:
