### ISSUE TITLE
Request: Provide usage documentation

### ISSUE THREAD

**Issue by whereswaldon** [github/codeql-go#158]
It'd be really nice to have a guide on how to use this repo correctly. Most of the CLIs bundled inside of it have little or no usage info. I *think* I managed to create a database correctly using `go-autobuilder`, but I'm really not sure. I had to set a couple environment variables (the purpose of which I could only guess). I imagine that such docs would help both random interested parties like me and new members of your team.

**Comment by sauyon** [comment]
See the usage section of the readme; the tools are meant to be called by the `codeql` cli tool.

However, I think documenting some of these externally would be useful for those interested in writing extractors, but that's not a priority at the moment.

**Comment by intrigus-lgtm** [comment]
I'd be interested in documentation on how to write an extractor.
But I can also understand that this is not a priority for you now.

**Comment by whereswaldon** [comment]
@sauyon When I visited this page, I had not yet discovered the existence of the `codeql` CLI. It's actually kinda hard to find if you start at y'all's GitHub repos, and the docs for it exist on an entirely different doc platform. I think that just linking to [here](https://help.semmle.com/codeql/codeql-cli.html) in the README would be all that is needed.
