### ISSUE TITLE
Master branch lost ability to track taint from parameter to receiver

### ISSUE THREAD

**Issue by gagliardetto** [github/codeql-go#159]
A taint-tracking class like this:

```codeql
	private class ReaderReset extends TaintTracking::FunctionModel, Method {
	  // signature: func (*Reader).Reset(r io.Reader)
	  ReaderReset() { this.(Method).hasQualifiedName("bufio", "Reader", "Reset") }

	  override predicate hasTaintFlow(FunctionInput inp, FunctionOutput outp) {
	    inp.isParameter(0) and outp.isReceiver()
	  }
	}
```

will **not** taint-track code like this:

```golang
func TaintStepTest_BufioReaderReset(r io.Reader) {
	// The flow is from `r` into `reader`.

	// Declare `reader` variable:
	var reader bufio.Reader

	// Call the method that **should** transfer the taint
	// from the parameter `r` to the receiver `reader`
	// (`reader` should now be tainted).
	reader.Reset(r)

	// Sink the tainted `reader`:
	sink(reader)
}
```

This problem was brought up before in https://github.com/github/codeql-go/pull/118#discussion_r416752705

The underlying issue was solved/patched before (I believe in https://github.com/github/codeql-go/commit/0546c527afcb470589d17c597a034b55955c8c10)

Thanks!

**Comment by max-schaefer** [comment]
Thank you for your report. I don't think your example would ever have worked, so it's not a regression as such, but it certainly should work. #161 makes it so.

**Comment by gagliardetto** [comment]
Awesome! Thanks a lot!
