### ISSUE TITLE
How to propagate taint from Lhs to Rhs in a field assignment

### ISSUE THREAD

**Issue by gagliardetto** [github/codeql-go#230]
Given this scenario:

```golang
func someFunc(ptr uintptr) {
	type SomeStruct struct {
		Hello uintptr
	}

	evilStruct := &SomeStruct{}
	evilStruct.Hello = ptr
}

```

Is it possible to propagate taint from `evilStruct` to `ptr`, so that a flow config with source `evilStruct` and sink `ptr` could succeed?

**Comment by max-schaefer** [comment]
I believe this should work:

```ql
override predicate isAdditionalTaintStep(DataFlow::Node pred, DataFlow::Node succ) {
  exists(DataFlow::Write w, Field f |
    w.writesField(pred, f, succ)
  )
}
```

I'm not sure why you would want to do this, though.

**Comment by gagliardetto** [comment]
Two flows converge to the same **sink** (starting from two different **sources**).

The query needs to compare the two **sources** (and optionally show the complete path).

AFAIK, there is no way to concatenate the nodes of two paths (or maybe there is?), so the idea is transform the second **source** to the **sink**.

![Untitled Diagram](https://user-images.githubusercontent.com/15271561/85845537-13f0e100-b7ad-11ea-9ee3-28acf12865c5.png)

Changing the direction of all taint tracking logic might not be possible, so for now I'll settle for showing one source, and then adding a meaningful message that explains the issue without showing the second source.

**Comment by max-schaefer** [comment]
Thank you for the explanation. I agree that trying to reverse the direction of flow is going to be difficult and problematic. Unfortunately I don't think there is a good way of showing multiple paths as part of the same alert.
