### ISSUE TITLE
can not  create database with codeql-go

### ISSUE THREAD

**Issue by scbizu** [github/codeql-go#258]
It seems that the `go-autobuilder` binary is not included in this repo , so my db creation is failed due to the binary not found .

codeql-cli command : `codeql database create my_repo --language go`

Am I missing something ?

**Comment by smowton** [comment]
Have you run `make` in the root of the repo?

**Comment by scbizu** [comment]
Yep , but the utils.sh reminds me the go-autobuidler is in `/tools/platform/osx/bin/go-autobuilder` , but actually after I make , the binary is in `/tools/osx64/go-autobuilder`. What's going wrong ?

**Comment by scbizu** [comment]
It works after I cp the binary from `/tools/osx64/go-autobuilder` to `/tools/platform/osx/bin/go-autobuilder` (manually create) .

**Comment by sauyon** [comment]
I'm not sure what you're trying to do; those scripts aren't meant to be run by hand, they're legacy support for our old tool. Have you set up codeql? I believe we have usage information in our readme.

**Comment by smowton** [comment]
@sauyon I don't think he's running the utils.sh script directly, but rather `codeql database create` as in the OP -- utils.sh just contains a reference to the old directory structure.

@scbizu is it possible your `codeql` binary is itself out of date and using a legacy path? Is it maybe an alias for the old CLI? Could you run `codeql --version`?

**Comment by sauyon** [comment]
I failed to read, apologies...

First, it's unlikely you actually want to be using this repository to do create CodeQL databases; CodeQL ships with its own version of the Go extractor, which is more stable than the bleeding edge.

If that doesn't work you should probably file an issue with the folks who make the release over at github/codeql-cli-binaries.

If you want to contribute to the codeql-go extractor (thanks!) would you mind putting up an issue for what you'd like to change? That way we know what you'd be working on and can guide you a bit better.

**Comment by scbizu** [comment]
Sorry for the delay .

@smowton  My codeql-cli version is 2.2.4 .  And I don't know why I trigger the legacy's way . (maybe it only works with the codeql-cli itself ? )

@sauyon I did create the database with cli's default go extractor , but it doesn't contain the ql/src/xxx.ql for testing purpose, so I cloned codeql-go as my extractor though ( it seems I used the legacy one ? ) .

**Comment by smowton** [comment]
Could you post the log from a minimal failing example?

**Comment by scbizu** [comment]
OK , I will try to describe the minimal falling case: 

* Download the release from the `code-ql-cli-binary` to my `$HOME/codeql-home` (and then the language specified codeql path is `$HOME/codeql-home/lang`, such as `$HOME/codeql-home/cpp`)
* Add the binary to my PATH , `export PATH=$PATH:/$HOME/codeql-home/codeql`
* `git clone` codeql-go to my `$HOME/codeql-home` (and the codeql-go path is `$HOME/codeql-home/codeql-go`)
* Remove the codeql-cli's builtin Go support (since it will be conflict with `codeql-go`,and the builtin Go extension has fewer `.ql` rules).
* And then `make` codeql-go to make the `go-autobuilder` and other binaries out .
-----------THE PRESENTATION IS DONE------------
* Then I try to create my database at `$HOME/codeql-home/`
* It successfully recognizes the codeql-go as the Go language extension , but codeql-go says :

<details>
<summary>Toggle to show logs</summary>
<p>

```shell
Initializing database at $HOME/codeql-home/codeql-go/MY_DATABASE. 
Running command [$HOME/codeql-home/codeql-go/tools/index.sh] in GO_PROJECT_PATH.
[2020-07-20 11:01:13] [ERROR] Spawned process exited abnormally (code 1; tried to run: [$HOME/codeql-home/codeql-go/tools/index.sh])
[2020-07-20 11:01:13] [build-err] +++ dirname $HOME/codeql-home/codeql-go/tools/index.sh
[2020-07-20 11:01:13] [build-err] ++ cd $HOME/codeql-home/codeql-go/tools
[2020-07-20 11:01:13] [build-err] ++ pwd
[2020-07-20 11:01:13] [build-err] + SCRIPTDIR=$HOME/codeql-home/codeql-go/tools
[2020-07-20 11:01:13] [build-err] + source $HOME/codeql-home/codeql-go/tools/utils.sh
[2020-07-20 11:01:13] [build-err] ++ '[' -z '' ']'
[2020-07-20 11:01:13] [build-err] ++ case "$OSTYPE" in
[2020-07-20 11:01:13] [build-err] ++ SEMMLE_PLATFORM=osx
[2020-07-20 11:01:13] [build-err] ++ '[' osx = win ']'
[2020-07-20 11:01:13] [build-err] ++ EXE=
[2020-07-20 11:01:13] [build-err] + run go-autobuilder
[2020-07-20 11:01:13] [build-err] + cmd=go-autobuilder
[2020-07-20 11:01:13] [build-err] + shift
[2020-07-20 11:01:13] [build-err] + $HOME/codeql-home/codeql-go/tools/platform/osx/bin/go-autobuilder
[2020-07-20 11:01:13] [build-err] $HOME/codeql-home/codeql-go/tools/utils.sh: line 23: $HOME/codeql-home/codeql-go/tools/platform/osx/bin/go-autobuilder: No such file or directory
A fatal error occurred: Exit status 1 from command: [$HOME/codeql-home/codeql-go/tools/index.sh]
```

</p>
</details>

* I post this issue after I see the log
* And then I just cp the binary from `/tools/osx64/go-autobuilder` to `/tools/platform/osx/bin/go-autobuilder` , and it works again .

**Comment by sauyon** [comment]
> codeql-cli command : `codeql database create my_repo --language go`

I probably should have read this better. This isn't how you specify the repository. See the output of `codeql database create --help` or [the online docs](https://help.semmle.com/codeql/codeql-cli/procedures/create-codeql-database.html).

For quick reference, this should look like `codeql database create <database> --source-root <your repo> --language go`.

Source root defaults to the working directory. My guess is you're trying to create a database using our code as a base.

In particular, I notice you don't seem to be passing the `codeql-go` path in the `codeql` command you pasted above, so I'm not sure how this is being resolved.

>     * Remove the codeql-cli's builtin Go support (since it will be conflict with `codeql-go`,and the builtin Go extension has fewer `.ql` rules).

Why and how are you doing this? I don't believe this is in the documentation anywhere. Indeed, this will probably break things.

>     * It successfully recognizes the codeql-go as the Go language extension , but codeql-go says :

What do you mean by it successfully recognizes the language extension? I assume `codeql resolve languages` gives `go (<path to codeql-go/build/codeql-extractor-go)`?

If you're trying to run queries I would highly recommend running them with the [plugin for VSCode](https://help.semmle.com/codeql/codeql-for-vscode/procedures/setting-up.html). If you set everything up according to the documentation, you shouldn't need this repository at all; it's included in the very convenient VSCode starter workspace.

**Comment by sauyon** [comment]
Ah, I think I have the actual solution to this mystery. Have you copied the entire `codeql-go` repository over the `go` directory that comes with the CodeQL CLI?

**Comment by scbizu** [comment]
> Ah, I think I have the actual solution to this mystery. Have you copied the entire `codeql-go` repository over the `go` directory that comes with the CodeQL CLI?

Yes, you are right . I  `rm -rf   go/`  and replace it with codeql-go. That's my `codeql resolve language`:
```
cpp (/Users/scnace/Projects/ezbuy/codeql/cpp)
csharp (/Users/scnace/Projects/ezbuy/codeql/csharp)
go (/Users/scnace/Projects/ezbuy/codeql/codeql-go)
java (/Users/scnace/Projects/ezbuy/codeql/java)
javascript (/Users/scnace/Projects/ezbuy/codeql/javascript)
python (/Users/scnace/Projects/ezbuy/codeql/python)
xml (/Users/scnace/Projects/ezbuy/codeql/xml)
```
my Go extractor is now codeql-go rather than go. Does It bring the breaks ? 

Ah, I think I just got your point , I will try to create database again , thank you ~

**Comment by scbizu** [comment]
I finally realized that this code-ql repo is not the language pack itself , but the ql pack . 

Thanks again for your time . I will close this issue.

**Comment by smowton** [comment]
Glad we got to the bottom of this in the end, thanks @sauyon!
