### ISSUE TITLE
Smaller issues with PrintAST

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql-go#265]
In #260 and #264, the `printAST` query was created and fixed up. There are still a few smaller issues. I'm breaking them into a new issue since this shouldn't prevent merging and closing of previous issues. I'm not even sure if everything here should be fixed:

* Method declaration receivers are not in parameter list (or anywhere in the ast)
* The FunctionName node is child of the FuncDecl/MethodDecl, though it seems more appropriate for it to be a child of the FuncTypeExpr since its source location is fully contained in that node.
* There is a File ast node, which has no source locations and no children. For the purposes of the AST viewer, it's not very interesting. Would be nice if we could exclude this.
* There is no Package statement node, but the identifier of the package statement is a node. So in here:

  ```go
  package json
  ```

  there is no node for `package json`, but there is one for `json`, which is a direct decedent of the root node. And this is causing ordering issues in the AST viewer.

**Comment by smowton** [comment]
Could you give an example of point 3, the empty file node? I've only ever seen them as roots with FuncDecl and other Decl children

**Comment by aeisenberg** [comment]
Here's an example of 3 and 4, directly from the ast viewer. 


<img width="482" alt="_Extension_Development_Host__-_decode_go__read-only__—_vscode-codeql-starter__Workspace_" src="https://user-images.githubusercontent.com/363559/88190538-3bda3580-cbef-11ea-9302-6ba84084049d.png">

I am running it on this file in a database downloaded from lgtm:

https://lgtm.com/projects/g/docker/go/latest/files/canonical/json/decode.go?sort=name&dir=ASC&mode=list

I guess there's a chance that it's something wrong in the viewer code, so let me look at that too.

**Comment by aeisenberg** [comment]
Regardless, since we are only and always parsing a single file, the file node is superfluous in this situation. Would it be possible to remove it completely from the tree?

**Comment by smowton** [comment]
Re: point 3, I think this must be an AST viewer bug? I don't know how to use it, but I attach the graphtext output for the same query using `File selectedSourceFile() { result.getRelativePath() = "canonical/json/decode.go" }`:

**Comment by smowton** [comment]
```
chris@orchard:/tmp$ head /tmp/xyz/go/print-ast.txt 
/canonical/json/decode.go:
#    0| [File] canonical/json/decode.go
#   10|   113: [ImportDecl] import declaration
#   11|     0: [ImportSpec] import specifier
#   11|       0: [StringLit] "bytes"
#   12|     1: [ImportSpec] import specifier
#   12|       0: [StringLit] "encoding"
```

That's the only File node involved.

It's possible of course to omit that our side, but it would make it more complicated to keep the child nodes properly ordered and labelled-- if it does have children are you happy to keep it? If not, is it easy to omit that node from the treeviewer control?

**Comment by smowton** [comment]
Re: point 1, test file:
```
package main

type obj struct {
}

func (recv obj) f() { }

func main() {
  var o obj
  o.f()
}
```

**Comment by smowton** [comment]
Re: point 2, the name falling under the FuncDecl but not under the type expression (which is common with anonymous function literals)

**Comment by aeisenberg** [comment]
This all makes sense. And let me look at the why the function decl has no children in the viewer when I get a chance.

**Comment by smowton** [comment]
@aeisenberg fix for point 4 -- see the graphtext diff in https://github.com/github/codeql-go/pull/267 for the change made.

There are various other nodes where it would be good to name rather than number the children, but I'll stick to just this one which is flagrantly misordered for the time being.

**Comment by smowton** [comment]
@aeisenberg are any of these still outstanding for you, or can we close?

**Comment by aeisenberg** [comment]
Yes! All is good.
