### ISSUE TITLE
Go contextual queries (find definitions and references) are not working

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql-go#357]
Conextual queries for find references and definitions are not returning any results for go in VS Code. Currently using 2ba9bbfd8ba1818b5ee9f6009c86a605189c9ef3 in the latest release of VSCode extension for codeql and master of vscode-codeql-starter workspace.

To reproduce:

1. Install https://lgtm.com/projects/g/kubernetes/kubernetes/ into vscode as a go database
2. Open `src/opt/src/cmd/verifydependencies/verifydependencies.go`
3. On line 178, select `collector` right-click -> find references

BUG
Expected: References to that symbol are found on line 186 and elsewhere
Actual: no references

Similarly, select the `collector` symbol on line 186 and invoke _Go to Definition_. No results are found.

See also https://github.com/github/codeql/issues/4351 for a similar problem in C#.

**Comment by max-schaefer** [comment]
Thank you for your report. I'm trying to reproduce, but...

> On line 178

[verifydependencies.go](https://lgtm.com/projects/g/kubernetes/kubernetes/latest/files/cmd/verifydependencies/verifydependencies.go) only seems to have 101 lines. Am I looking at the wrong file?

I've tried a few other jump-to-definitions, and they all seem to work.

**Comment by aeisenberg** [comment]
Oops. Sorry. Pasted the wrong file. It is `src/opt/src/cmd/preferredimports/preferredimports.go`. Thanks for taking a look.

**Comment by max-schaefer** [comment]
Thank you for the update. I have now found the location you reported, but am unable to consistently reproduce. I think I got it to fail once, but since then it's been resolving references correctly every time I've tried again, so I'm kind of doubting my recollection of the time it failed, I may have just clicked on the wrong button then.

**Comment by aeisenberg** [comment]
Sorry for the noise, but this is looking like a vscode-codeql issue. It is not properly handling databases downloaded from LGTM whose source folders are unzipped. See the explanation here: https://github.com/github/codeql/issues/4351

I'll close this issue.
