### ISSUE TITLE
Fix Xpath library

### ISSUE THREAD

**Issue by intrigus-lgtm** [github/codeql-go#367]
Comparing https://github.com/github/codeql-go/blob/d31b4d262f4962da2407777fa3910d79335e8d3b/ql/src/semmle/go/frameworks/XPath.qll#L8-L16
with
https://github.com/github/codeql-go/blob/d31b4d262f4962da2407777fa3910d79335e8d3b/ql/src/semmle/go/frameworks/SQL.qll#L8-L29
it seems, I made a mistake when doing my XPath PR.

If this is indeed wrong, feel free to fix it as I currently have no time for fixing it.

**Comment by sauyon** [comment]
You're absolutely correct, thank you.
