### ISSUE TITLE
Access map key

### ISSUE THREAD

**Issue by jason-invision** [github/codeql-go#377]
How would I access the key used when reading an element of a map?

For example,
```
id := vars["id"]
```
If I traced the dataflow to `vars` how would I output `"id"`?

**Comment by smowton** [comment]
Have you tried looking for a `DataFlow::ElementReadNode` that `reads(base, element)`? Here the `base` would be `vars` which it sounds like you already have a node for, and `element` would be `"id"`, so `element.getStringValue()` would extract the constant.

**Comment by jason-invision** [comment]
When I use `DataFlow::ReadNode` I get results, but when I switch to `DataFlow::ElementReadNode` I don't.

For example,
```
from DataFlow::ReadNode node, MapType mapType
where node.getType() = mapType
select node
```
vs.
```
from DataFlow::ElementReadNode node, MapType mapType
where node.getType() = mapType
select node
```

**Comment by jason-invision** [comment]
This also doesn't return any results

```
from DataFlow::ReadNode node, MapType mapType, DataFlow::Node index
where node.getType() = mapType
and node.readsElement(node, index)
select node, index
```

**Comment by jason-invision** [comment]
Looks like the solution is this:

```
from DataFlow::ElementReadNode node, MapType mapType
where node.getBase().getType() = mapType
select node, node.getIndex(), node.getIndex().getStringValue()
```
