### ISSUE TITLE
False positive for backspace character used in regexp

### ISSUE THREAD

**Issue by mislav** [github/codeql-go#397]
This line triggered a CodeQL warning in the `cli/cli` repo:
```go
var placeholderRE = regexp.MustCompile(`\:(owner|repo|branch)\b`)
```

The warning says:
> A regular expression used here contains a literal backspace `\b`; did you mean `\b`, a word boundary?

And in its "recommendation" section, it says:
> Alternatively, you can use backtick-delimited raw string literals. For example, the `\b` in `regexp.Compile(`hello\bworld`)` matches a word boundary, not a backspace character, as within backticks `\b` is not an escape sequence.

Well, we are using backtick-delimited raw string literal in the "offending" code, and it should be trivial for CodeQL to detect that. I think that CodeQL is convinced that we've passed a double-quoted string literal as argument to `regexp.MustCompile()`, which could be indicative of a deeper, more serious problem in CodeQL for Go.

**Comment by smowton** [comment]
This is fixed by https://github.com/github/codeql-go/pull/395
