### ISSUE TITLE
[Bug] For ... range not found

### ISSUE THREAD

**Issue by sh7dm** [github/codeql-go#446]
Query some repo with this CodeQL:
```codeql
import go

from ForStmt f
select f
```
Expected: `for` loops with `range` statement are available in output
Seen: no such loops found in code, only other types of `for` in output

**Comment by owen-mc** [comment]
To find those, use `RangeStmt`. If you want to find both, use `LoopStmt`.

You may find this a helpful resource: https://codeql.github.com/docs/codeql-language-guides/abstract-syntax-tree-classes-for-working-with-go-programs/

Another useful resource for answering this kind of question is the AST class viewer, available in the most recent version of the CodeQL extension for Visual Studio Code.

**Comment by sh7dm** [comment]
Thank you! Sorry for misunderstanding those statement types.

**Comment by owen-mc** [comment]
It's an easy mistake to make - hopefully those resources will make that kind of thing easier in future.

**Comment by sh7dm** [comment]
Yes, that docs page is very convenient!
