### ISSUE TITLE
Is the response to a remote HTTP call an `UntrustedFlowSource`?

### ISSUE THREAD

**Issue by gagliardetto** [github/codeql-go#523]
If I have an HTTP client, and I do a HTTP request to a remote server, does the response data count as `UntrustedFlowSource`?

**Comment by sauyon** [comment]
I would say no in general; most of the time that's not an issue because of HTTPS. If you meant HTTP specifically, then maybe.

**Comment by gagliardetto** [comment]
So when modeling a web framework (that is also a HTTP client) I should **not** include response data as `UntrustedFlowSource` by default, right?

**Comment by sauyon** [comment]
Yep, that's right.

**Comment by smowton** [comment]
Agreed!
