### ISSUE TITLE
Was `HTTP::HeaderRead` ever modeled?

### ISSUE THREAD

**Issue by gagliardetto** [github/codeql-go#548]
I found a note of mine from a long time ago that mentions `HTTP::HeaderRead`, but I cannot find the model.

Was it ever modeled?

Should it be modeled?

**Comment by smowton** [comment]
I don't know of a QL class by that name or a Go type or function. Do you know what it is?

**Comment by gagliardetto** [comment]
Oh, then it was a figment of my imagination :laughing: 

Anyway, `HTTP::HeaderRead` is the sister model of `HTTP::HeaderWrite`.

I considered implementing it for the CORS query, but then went with the `UntrustedFlowSource` instead.

Then it appeared in old notes I had from a year ago.
