### ISSUE TITLE
[tainttracking] no taint for fields set

### ISSUE THREAD

**Issue by hshenCode** [github/codeql-go#582]
let's say A is a struct  with fields {userid,  username},  B is untrusted source,    A.userid = B

I expect that A'll be tainted, but actually not..
I check the source code in the function 'localAdditionalTaintStep', seems it doesn't cover this action..

So if I want to let A be tainted by B,  what can I do in my overrided function 'isAdditionalTaintStep'?

Thanks very much!!

**Comment by hshenCode** [comment]
I tried this:

**Comment by smowton** [comment]
Yes, that's right: generally we distinguish a tainted field from a whole tainted object.

As an alternative to writing an additional taint step at a write site, in the near future when the Go dataflow library is updated we will gain support for the `allowImplicitRead` predicate seen here in the Java library: https://github.com/github/codeql/blob/main/java/ql/lib/semmle/code/java/dataflow/internal/DataFlowImpl2.qll#L88

This will indicate that (for example) `FieldContent` can be implicitly read out of a struct at a sink node, such that `sink(A)` is treated like `sink(A.userid)`. In Java some forms of content (array and Collection content) are treated this way by default in TaintTracking but not DataFlow configurations; in Go we will likely mimic this choice.
