### ISSUE TITLE
CWE-117 false positive: %q formatting directive

### ISSUE THREAD

**Issue by rhcarvalho** [github/codeql-go#650]
Similar to #635.

The suggested mitigation for "Improper Output Neutralization for Logs" includes performing a string replacement of `"\n"` characters using `strings.Replace`.

The [`"%q"` formatting directive](https://pkg.go.dev/fmt#hdr-Printing) (double-quoted string safely escaped with Go syntax) is also a form of escaping user input, in particular for plain-text logs, as it escapes non-printable characters (including `"\n"`, `"\r"`, `"\t"`, etc).

However, code using `log.Printf("%q", ...)`  is still considered unsafe by CodeQL scanning.

Here's an example run:
https://github.com/getsentry/sentry-go/pull/399/checks?check_run_id=4583764415

![image](https://user-images.githubusercontent.com/88819/146798350-e11cfeb3-b12d-4e8d-97ab-756c950040bf.png)

Would it be possible to teach CodeQL about `"%q"`? There are also variations, such as `"%+q"`, "`%#q`, `"%060q"`, `% q`, `%[2]q`, etc, with the complete parsing rules being non-trivial.

Perhaps use the fact that [`fmt.(*fmt).fmtQ`](https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/fmt/format.go;l=444-459;drc=refs%2Ftags%2Fgo1.17.5) is called [before writing to the `io.Writer` where the log message is going](https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/fmt/print.go;l=204-205;drc=refs%2Ftags%2Fgo1.17.5).

**Comment by adityasharad** [comment]
Thanks for the suggestion. I've passed this on to the CodeQL Go team for consideration in the new year.

**Comment by smowton** [comment]
Candidate solution: https://github.com/github/codeql-go/pull/658

**Comment by smowton** [comment]
Fixed in 2.8.0 (by #658), which has now been released, so the fix should appear in the next few days as it comes into use on Code Scanning. To be certain whether 2.8.0 was used in a particular analysis, search for codeql version in the CodeQL Action's log.
