### ISSUE TITLE
⚡ Zap survey

### ISSUE THREAD

**Issue by CleanCut** [github/codeql-go#708]
👋🏻 Hi, folks! I'm here on behalf of @github/frameworks-services.  We're [researching](https://github.com/github/frameworks-services/issues/243) how and why teams are using the `zap` module (`go.uber.org/zap`) to help us in our development planning and inform the Go guidance we provide to internal teams.

From my research, it appears @github/codeql-go  is using `zap` in the following repository/repositories:

- github/codeql-go

# Questions

- Which environment(s) are the above repositories used in? (dotcom, GHAE, GHES, and/or other)
  - Is your logging (with `zap`) configured & enabled in all the environment(s) the repositories are used in?
- Why are you using `zap` instead of some other module? (ie was it an arbitrary choice, or did you have specific reason(s)?)
- Are you familiar with the internal `go-log` module?
  - If yes, are you aware of any feature gaps between `zap` and `go-log` or other obstacles that would make it difficult to switch from `zap` to `go-log`?
- Do you use any structured logging modules other than `zap` in your team? (If yes, please list them)
- What pain points / friction do you have with logging modules?

**Comment by smowton** [comment]
N/A, we don't use it, you've found stubs used for testing purposes.
