### ISSUE TITLE
False positive with CWE-190 / CWE-681

### ISSUE THREAD

**Issue by MichaelUrman** [github/codeql-go#717]
Running the GitHub CodeQL scanning actions on the following code reports what I believe is a false positive CWE-190 / CWE-681:

```go
package main

import (
    "os"
    "strconv"
)

func main() {
    for _, arg := range os.Args[1:] {
        n, err := strconv.ParseInt(arg, 10, 0)
        if err == nil {
            var itf interface{} = n
            i32 := itf.(int32)
            println(i32)
        }
    }
}
```

On line 13 (`i32 := itf.(int32)`) it reports:
> Incorrect conversion of an integer with architecture-dependent bit size from  to a lower bit size type int32 without an upper bound check.

However this is not a type conversion, this is a type assertion.  When `itf` holds a type other than int32, the above code panics. (Perhaps that should be a different error.) Neither the logically equivalent type switch nor the two-valued type assertion report this.

```go
            var i32 int32
            switch x := itf.(type) {
            case int32:
                i32 = x
            default:
                panic("bad type")
            }
            println(i32)
```

```go
            i32, ok := itf.(int32)
            println(i32, ok)
```

The code from which this was extracted is an implementation of an interface similar to [sql.Scanner](https://pkg.go.dev/database/sql#Scanner), hence the indirection through an empty interface.

**Comment by owen-mc** [comment]
Thanks for taking the time to report this. It does indeed look like a very clear error. The fix is very easy, and has just been merged. If you are using code scanning then I think it is updated every two weeks or so, so you should get the fixed version in roughly that timeframe.

**Comment by MichaelUrman** [comment]
Thanks for both the rapid turnaround and for answering my "when will I get it?" question before I even asked it!
