### ISSUE TITLE
v1.27.0 tag is missing the install-reps.sh script

### ISSUE THREAD

**Issue by aeisenberg** [github/codeql-go#721]
The scripts/install-reps.sh file is missing on the v1.27.0 tag. I'm guessing we never merged that file into the lgtm branch. At this point, since codeql-go is being merged into codeql, this may not need to be fixed, but raising it anyway to make sure we are aware of the missing file.

Originally reported in https://github.com/github/codeql/issues/8763

**Comment by smowton** [comment]
You mean install-deps.sh? That was only written in Aug 2021 (https://github.com/github/codeql-go/commits/main/scripts/install-deps.sh), while https://github.com/github/codeql-go/releases/tag/lgtm%2Fv1.27.0 predates it by 3 months

**Comment by aeisenberg** [comment]
Ah...that's right. Thanks. I saw the last commit on that tag as March 5, but I failed to see it was 2021.

**Comment by aeisenberg** [comment]
Not much we can or should do about this.
