### ISSUE TITLE
Could not resolve module go. There should probably be a qlpack.yml file declaring dependencies in...

### ISSUE THREAD

**Issue by briwild** [github/codeql-go#733]
I was setting up everything to run codeql cli for golang and was able to create the database, but when running the command to analyze the database, an error was returned:

Command I run: `codeql database analyze ./database go1.ql --format=csv --output=output.csv`

Output of the terminal:
> Running queries.
> Compiling query plan for /Users/<username>/projects/<repository_name>/go1.ql.
> ERROR: Could not resolve module go. There should probably be a qlpack.yml file declaring dependencies in /Users/<username>/projects/<repository_name> or an enclosing directory. (/Users/<username>/projects/<repository_name>/go1.ql:1,8-10)

The content of the go1.ql file is the following:

> import go
> 
> select "hello world"

The steps I followed for installing codeql and codeql-go were the following:
* https://codeql.github.com/docs/codeql-cli/getting-started-with-the-codeql-cli/#checking-out-the-codeql-source-code-directly
* https://github.com/github/codeql-go#installation

Pages I have read to understand the problem that the terminal returned:
* https://codeql.github.com/docs/codeql-cli/about-ql-packs/
* https://codeql.github.com/docs/ql-language-reference/modules/#importing-modules
* https://codeql.github.com/docs/ql-language-reference/name-resolution/#name-resolution
* https://codeql.github.com/docs/ql-language-reference/ql-language-specification/#module-resolution

After all this research, I couldn't fix it and make this work in the terminal. Has anyone had the same problem and could solve the issue? Thanks in advance.

**Comment by briwild** [comment]
Somehow codeql can't find the codeql/go-all package:
```
╰─❯ codeql resolve languages
go (/Users/my-username/codeql-home/codeql-repo/go)
python (/Users/my-username/codeql-home/codeql-repo/python)
java (/Users/my-username/codeql-home/codeql-repo/java)
html (/Users/my-username/codeql-home/codeql-repo/html)
xml (/Users/my-username/codeql-home/codeql-repo/xml)
properties (/Users/my-username/codeql-home/codeql-repo/properties)
cpp (/Users/my-username/codeql-home/codeql-repo/cpp)
csv (/Users/my-username/codeql-home/codeql-repo/csv)
csharp (/Users/my-username/codeql-home/codeql-repo/csharp)
javascript (/Users/my-username/codeql-home/codeql-repo/javascript)
ruby (/Users/my-username/codeql-home/codeql-repo/ruby)


╰─❯ codeql resolve qlpacks                         
codeql/go-all (/Users/my-username/codeql-home/codeql-go/ql/lib)
codeql/go-examples (/Users/my-username/codeql-home/codeql-go/ql/examples)
codeql/go-queries (/Users/my-username/codeql-home/codeql-go/ql/src)
codeql/go-tests (/Users/my-username/codeql-home/codeql-go/ql/test)
codeql/suite-helpers (/Users/my-username/.codeql/packages/codeql/suite-helpers/0.0.2)
legacy-libraries-go (/Users/my-username/codeql-home/codeql-go/ql/config/legacy-support)
legacy-upgrades (/Users/my-username/codeql-home/codeql-repo/legacy-upgrades)


╰─❯ codeql database analyze ./database go1.ql --format=csv --output=output.csv
Running queries.
ERROR: Referenced pack 'codeql/go-all' not found. (/Users/my-username/projects/my-project/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /Users/my-username/projects/my-project
```

Do you know if there is something else that I'm missing? It's my first time setting up codeql, so maybe there is something that I missed.

**Comment by smowton** [comment]
Try a `bash scripts/install-deps.sh` in the root of `codeql-go`?

**Comment by briwild** [comment]
Still returning the same error. Here the output:
```
~/codeql-home/codeql-go main
╰─❯ bash scripts/install-deps.sh
Dependencies resolved. Installing packages...
Install location: /Users/my-username/.codeql/packages
Nothing to install.
Dependencies resolved. Installing packages...
Install location: /Users/my-username/.codeql/packages
Dependencies resolved. Installing packages...
Install location: /Users/my-username/.codeql/packages
Dependencies resolved. Installing packages...
Install location: /Users/my-username/.codeql/packages
Nothing to install.

╭─ ~/codeql-home/codeql-go main
╰─❯ cd ~/projects/my-project

╭─ ~/projects/my-project main
╰─❯ codeql database analyze ./database go1.ql --format=csv --output=output.csv
Running queries.
ERROR: Referenced pack 'codeql/go-all' not found. (/Users/my-username/projects/my-project/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for /Users/my-username/projects/my-project
```

**Comment by aeisenberg** [comment]
Have you run `codeql pack install` in the directory containing your `qlpack.yml`? It looks like `codeql/go-all` was never downloaded from the registry. Please run that command first, and try again.

Unfortunately, `codeql resolve qlpacks` does not behave properly when the only packs installed are in `codeql-home`, sitting next to the unzipped `codeql` binaries. (This will be fixed in the next release of codeql). If you prefer to use the checked out version of codeql-go, then you can use `--additional-packs`, like this:

```
$ codeql database analyze --additinal-packs /Users/my-username/codeql-home/codeql-go/ql/lib ./database go1.ql --format=csv --output=output.csv
```

**Comment by briwild** [comment]
Sorry for the late response. Had Covid over the last few days and couldn't check again for this. Let me check if that helps and will let you know soon.

**Comment by briwild** [comment]
It works! Just to also let documentation for any other person that wants to start with codeql for golang, I followed also these other links to finish running for the first time codeql for golang:

- https://github.com/github/codeql-go/blob/main/ql/examples/snippets/incompleteswitchoverenum.ql
- http://www.safe6.cn/article/248

When running `codeql database analyze ./database go1.ql --format=csv --output=output.csv --rerun`, the output is correct. So thanks everyone for helping me solving the issue! I appreciate your help :)

**Comment by smowton** [comment]
Thanks for following up!
